# Use the latest 2.1 version of CircleCI pipeline process engine. 
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  # The Node.js orb contains a set of prepackaged CircleCI configuration you can utilize
  # Orbs reduce the amount of configuration required for common tasks. 
  # See the orb documentation here: https://circleci.com/developer/orbs/orb/circleci/node
  node: circleci/node@4.5.1

jobs:
    build:
        docker:
            - image: circleci/node:current

        working_directory: ~/repo

        steps:
            - checkout

            - restore_cache:
                  keys:
                      - dependency-cache-1-{{ checksum "package-lock.json" }}

            - run: npm install

            - save_cache:
                  paths:
                      - node_modules
                  key: dependency-cache-1-{{ checksum "package-lock.json" }}

            - persist_to_workspace:
                  root: "."
                  paths:
                      - ./*
                      - node_modules
                      - package-lock.json
                      - src

    eslint:
        docker:
            - image: circleci/node:current

        working_directory: ~/repo

        steps:
            - checkout

            - attach_workspace:
                  at: "."

            - run: npm run eslint

    publish:
        docker:
            - image: circleci/node:current

        working_directory: ~/repo

        steps:
            - checkout

            - attach_workspace:
                  at: "."

            - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc

            - run: npm publish || exit 0

    prettier:
        docker:
            - image: circleci/node:current

        working_directory: ~/repo

        steps:
            - checkout

            - attach_workspace:
                  at: "."

            - run: npm run prettier

    test:
        docker:
            - image: circleci/node:current

        working_directory: ~/repo

        steps:
            - checkout

            - attach_workspace:
                  at: "."

            - run: npm run test:ci

    tsc:
        docker:
            - image: circleci/node:current

        working_directory: ~/repo

        steps:
            - checkout

            - attach_workspace:
                  at: "."

            - run: npm run tsc

            - persist_to_workspace:
                  root: "."
                  paths:
                      - src

workflows:
    version: 2
    commit:
        jobs:
            - build
            - eslint:
                  requires:
                      - build
            - publish:
                  filters:
                      branches:
                          only: main
                  requires:
                      - tsc
            - prettier:
                  requires:
                      - build
            - test:
                  requires:
                      - build
            - tsc:
                  requires:
                      - build
